title: Emilia Psacharopoulos
description: Full Stack Software Engineer
baseurl: ""
url: "https://emiliapsacharopoulos.github.io"

# Build settings
permalink: pretty
markdown: kramdown

collections:
  notes:
    output: true
    permalink: /notes/:name/
theme: null
plugins:
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .claude/
